/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as NotificationsRouteImport } from './pages/notifications'
import { Route as LoginRouteImport } from './pages/login'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ScripturesIndexRouteImport } from './pages/scriptures/index'
import { Route as ProfileIndexRouteImport } from './pages/profile/index'
import { Route as ProfileUserIdRouteImport } from './pages/profile/$userId'
import { Route as PostsNewRouteImport } from './pages/posts/new'
import { Route as PostsIdRouteImport } from './pages/posts/$id'
import { Route as ScripturesCollectionIndexRouteImport } from './pages/scriptures/$collection/index'
import { Route as ApiAuthCallbackRouteImport } from './pages/api/auth/callback'
import { Route as ScripturesCollectionBookIndexRouteImport } from './pages/scriptures/$collection/$book/index'
import { Route as ScripturesCollectionBookChapterRouteImport } from './pages/scriptures/$collection/$book/$chapter'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScripturesIndexRoute = ScripturesIndexRouteImport.update({
  id: '/scriptures/',
  path: '/scriptures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScripturesCollectionIndexRoute =
  ScripturesCollectionIndexRouteImport.update({
    id: '/scriptures/$collection/',
    path: '/scriptures/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ScripturesCollectionBookIndexRoute =
  ScripturesCollectionBookIndexRouteImport.update({
    id: '/scriptures/$collection/$book/',
    path: '/scriptures/$collection/$book/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScripturesCollectionBookChapterRoute =
  ScripturesCollectionBookChapterRouteImport.update({
    id: '/scriptures/$collection/$book/$chapter',
    path: '/scriptures/$collection/$book/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/new': typeof PostsNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/scriptures/': typeof ScripturesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/scriptures/$collection/': typeof ScripturesCollectionIndexRoute
  '/scriptures/$collection/$book/$chapter': typeof ScripturesCollectionBookChapterRoute
  '/scriptures/$collection/$book/': typeof ScripturesCollectionBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/new': typeof PostsNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile': typeof ProfileIndexRoute
  '/scriptures': typeof ScripturesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/scriptures/$collection': typeof ScripturesCollectionIndexRoute
  '/scriptures/$collection/$book/$chapter': typeof ScripturesCollectionBookChapterRoute
  '/scriptures/$collection/$book': typeof ScripturesCollectionBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/new': typeof PostsNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/scriptures/': typeof ScripturesIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/scriptures/$collection/': typeof ScripturesCollectionIndexRoute
  '/scriptures/$collection/$book/$chapter': typeof ScripturesCollectionBookChapterRoute
  '/scriptures/$collection/$book/': typeof ScripturesCollectionBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/$id'
    | '/posts/new'
    | '/profile/$userId'
    | '/profile/'
    | '/scriptures/'
    | '/api/auth/callback'
    | '/scriptures/$collection/'
    | '/scriptures/$collection/$book/$chapter'
    | '/scriptures/$collection/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/$id'
    | '/posts/new'
    | '/profile/$userId'
    | '/profile'
    | '/scriptures'
    | '/api/auth/callback'
    | '/scriptures/$collection'
    | '/scriptures/$collection/$book/$chapter'
    | '/scriptures/$collection/$book'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/$id'
    | '/posts/new'
    | '/profile/$userId'
    | '/profile/'
    | '/scriptures/'
    | '/api/auth/callback'
    | '/scriptures/$collection/'
    | '/scriptures/$collection/$book/$chapter'
    | '/scriptures/$collection/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsNewRoute: typeof PostsNewRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ScripturesIndexRoute: typeof ScripturesIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ScripturesCollectionIndexRoute: typeof ScripturesCollectionIndexRoute
  ScripturesCollectionBookChapterRoute: typeof ScripturesCollectionBookChapterRoute
  ScripturesCollectionBookIndexRoute: typeof ScripturesCollectionBookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scriptures/': {
      id: '/scriptures/'
      path: '/scriptures'
      fullPath: '/scriptures/'
      preLoaderRoute: typeof ScripturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scriptures/$collection/': {
      id: '/scriptures/$collection/'
      path: '/scriptures/$collection'
      fullPath: '/scriptures/$collection/'
      preLoaderRoute: typeof ScripturesCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scriptures/$collection/$book/': {
      id: '/scriptures/$collection/$book/'
      path: '/scriptures/$collection/$book'
      fullPath: '/scriptures/$collection/$book/'
      preLoaderRoute: typeof ScripturesCollectionBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scriptures/$collection/$book/$chapter': {
      id: '/scriptures/$collection/$book/$chapter'
      path: '/scriptures/$collection/$book/$chapter'
      fullPath: '/scriptures/$collection/$book/$chapter'
      preLoaderRoute: typeof ScripturesCollectionBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PostsIdRoute: PostsIdRoute,
  PostsNewRoute: PostsNewRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ScripturesIndexRoute: ScripturesIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ScripturesCollectionIndexRoute: ScripturesCollectionIndexRoute,
  ScripturesCollectionBookChapterRoute: ScripturesCollectionBookChapterRoute,
  ScripturesCollectionBookIndexRoute: ScripturesCollectionBookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
