/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as NotificationsRouteImport } from './pages/notifications'
import { Route as LoginRouteImport } from './pages/login'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ScripturesIndexRouteImport } from './pages/scriptures/index'
import { Route as ProfileIndexRouteImport } from './pages/profile/index'
import { Route as PostsNewRouteImport } from './pages/posts/new'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScripturesIndexRoute = ScripturesIndexRouteImport.update({
  id: '/scriptures/',
  path: '/scriptures/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/new': typeof PostsNewRoute
  '/profile/': typeof ProfileIndexRoute
  '/scriptures/': typeof ScripturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/new': typeof PostsNewRoute
  '/profile': typeof ProfileIndexRoute
  '/scriptures': typeof ScripturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/posts/new': typeof PostsNewRoute
  '/profile/': typeof ProfileIndexRoute
  '/scriptures/': typeof ScripturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/new'
    | '/profile/'
    | '/scriptures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/new'
    | '/profile'
    | '/scriptures'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notifications'
    | '/posts/new'
    | '/profile/'
    | '/scriptures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PostsNewRoute: typeof PostsNewRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ScripturesIndexRoute: typeof ScripturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scriptures/': {
      id: '/scriptures/'
      path: '/scriptures'
      fullPath: '/scriptures/'
      preLoaderRoute: typeof ScripturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PostsNewRoute: PostsNewRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ScripturesIndexRoute: ScripturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
